name: Build

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 */4 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2.1.2
        with:
          node-version: '18.x'

      - name: Cache pnpm modules
        uses: actions/cache@v2
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-

      - name: Cache downloads
        uses: actions/cache@v2
        with:
          path: ~/.cache
          key: ${{ runner.os }}-fetch-${{ hashFiles('.cache') }}
          restore-keys: |
            ${{ runner.os }}-fetch-

      - name: Install Packages Dependencies
        uses: pnpm/action-setup@v2.0.1
        with:
          version: 6
          run_install: |
            - recursive: true
              args: [--frozen-lockfile, --strict-peer-dependencies]

      - name: Build
        run: pnpm run build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          force_orphan: true

      - name: Keep workflow alive
        uses: gautamkrishnar/keepalive-workflow@v1
        with:
          commit_message: 'keep alive'
          committer_username: 'GitHub Action'
          committer_email: 'action@users.noreply.github.com'
